### ISSUE TITLE
Not syncing[BUG]

### ISSUE THREAD

**Issue by Pardison** [qbcore-framework/qb-vehicleshop#266]
**Describe the bug**
When you setup a new vehicle shop, 

**To Reproduce**
1. Create a new vehicle shop (or current one) on newest core 
2. Have 2 people, one of them swapping through the vehicles, and the other one just standing nearby
3. You will notice one of two things - either the vehicle just disappears and doesnt reappear (rare) or the more common issue is that they just start stacking ontop of eachother.
4. No errors

**Expected behavior**
They should be syncing properly where they don't stack 

**Screenshots**
![unknown (1)](https://user-images.githubusercontent.com/91909120/197345024-1caf3d91-c005-494b-81b9-1513522fe2f2.png)

**Questions (please complete the following information):**
 - When you last updated: yesturday
 - Are you using custom resource? which ones? just qbcore nothing that would interfere with vehicleshop
 - Have you renamed `qb-` to something custom? no

**Additional context**
N/A

**Comment by ellejah** [comment]
I've encountered this twice, the two common issues I had to resolve. 
1. Your car resources are not optimized. They are either in many folders, have mix-match manifests, or __resource lua. Try to set it up where all your cars are under one resource using a singular fxmanifest.lua. Tutorial: https://www.youtube.com/watch?v=j1P75HBcCgE
2. One or more cars exceed a texture threshold. If more than one person is toggling through cars, and those cars require a lot of resources to render, the system may glitch and cause this to happen. Review your cars individually to see which cars may impact the server. This is tedious, but just because you can stream the car doesn't mean it's optimized for actual use. You can tell it's not optimized by spawning it and running it into a wall. If it causes you and everyone around you to crash, the car is not optimized for use. You will need to evaluate each one of your cars.
